# DB에 저장된 상장기업 정보 불러오기

In [2]:
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/stock_info")
conn = engine.connect()

In [6]:
data

,주식종목,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,코스닥,한국피아이엠,44890,자동차 신품 부품 제조업,"내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행...",2025-04-04,12월,송준호,http://www.pimkorea.com,대구광역시
1,코스닥,에이유브랜즈,48107,"섬유, 의복, 신발 및 가죽제품 소매업","레인부츠, 스니커즈, 겨울화, 패션잡화 등",2025-04-03,12월,김지훈,http://aubrandz.irpage.co.kr,서울특별시
2,코스닥,우양에이치씨,10197,"구조용 금속제품, 탱크 및 증기발생기 제조업","화공 플랜트, 에너지 플랜트",2025-03-28,12월,김진태,http://www.wooyang.co.kr,경기도
3,코스닥,더즌,46286,전기 통신업,디지털뱅킹 솔루션(B2B 금융 서비스),2025-03-24,12월,조철한,http://www.dozn.co.kr/,서울특별시
4,코스닥,심플랫폼,44453,소프트웨어 개발 및 공급업,NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영),2025-03-21,12월,임대근..,http://simplatform.com/,서울특별시
...,...,...,...,...,...,...,...,...,...,...
2756,유가증권,유한양행,00010,의약품 제조업,"의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...",1962-11-01,12월,대표이..,http://www.yuhan.co.kr,서울특별시
2757,유가증권,CJ대한통운,00012,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,신영수..,http://www.cjlogistics.com,서울특별시
2758,유가증권,경방,00005,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준,..",http://www.kyungbang.co.kr,서울특별시
2759,유가증권,유수홀딩스,00070,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,http://www.eusu-holdings.com,서울특별시
2760,유가증권,한진중공업홀딩스,00348,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,조원국,http://www.hhic-holdings.com,경기도

# Npay증권에서 종목코드로 주가 조회 후 수집하기

In [9]:
stock_code = data['종목코드'].apply(lambda x: x+"0")
stock_code

0       448900
1       481070
2       101970
3       462860
4       444530
         ...
2756    000100
2757    000120
2758    000050
2759    000700
2760    003480
Name: 종목코드, Length: 2761, dtype: object

In [1]:
import time
import requests
from bs4 import BeautifulSoup as bs

In [125]:
final_result = []
for idx, code in enumerate(stock_code[1000:]):
    url =f"https://finance.naver.com/item/main.naver?code={code}"
    r = requests.get(url)
    print(r.status_code, f"{idx+1}/{len(stock_code)} 작업중", end="\r")
    soup = bs(r.content, 'lxml')
    # 종목명
    stock_name = soup.select_one("dl.blind > dd:nth-child(3)").text[4:]
    # 현재가
    today_price = int(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[1].replace(",", ""))
    # 변동금액
    change = soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[3:5]
    change = -int(change[1].replace(",", "").replace("\n,,", "")) if change[0] == "하락" else int(change[1].replace(",", "").replace("\n", ""))
    # 변동률
    percent = "".join(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[16:30])
    percent = percent.replace("마이너스", "-").replace("퍼센트", "%").replace("\n", "").replace("플러스", "")
    # 전일가
    yester_price = int(soup.select_one("dl.blind > dd:nth-child(6)").text[4:].replace(",", ""))
    # 고가
    hi = soup.select_one("dl.blind > dd:nth-child(8)").text[3:].replace(",", "")
    # 상한가
    top = soup.select_one("dl.blind > dd:nth-child(9)").text[4:].replace(",", "")
    # 저가
    low = soup.select_one("dl.blind > dd:nth-child(10)").text[3:].replace(",", "")
    # 하한가
    bottom = soup.select_one("dl.blind > dd:nth-child(11)").text[4:].replace(",", "")
    # 거래량
    volume = soup.select_one("dl.blind > dd:nth-child(12)").text[4:].replace(",", "")

    result = (code, stock_name, today_price, change, percent, yester_price, hi, top, low, bottom, volume)
    final_result.append(result)
    time.sleep(5)
    
columns = ["종목코드", "종목명", "현재가", "변동금액", "변동률", "전일가",
           "고가", "상한가", "저가", "하한가", "거래량"  ]    
df = pd.DataFrame(final_result, columns=columns)
df

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,448900,한국피아이엠,13870,-2230,-13.85%,16100,17720,20900,13690,11270,7378280
1,481070,에이유브랜즈,14370,-2590,-15.27%,16960,16130,22000,14350,11880,709156

In [134]:
from datetime import datetime
today = datetime.today()
date = f"{today.year}_{today.month:02d}"
print(date)

2025_04

In [137]:
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/stock_info")
conn = engine.connect()
df.to_sql(f'stock_price_{today.year}_{today.month:02d}', con=conn,  if_exists="append", index=False)
conn.close()

# 데이터 수집과 동시에 DB에 저장하기

In [151]:
import time
import requests
from bs4 import BeautifulSoup as bs

In [153]:
def year_month():
    from datetime import datetime
    today = datetime.today()
    return today.year, today.month

In [155]:
for idx, code in enumerate(stock_code[46]):
    url =f"https://finance.naver.com/item/main.naver?code={code}"
    r = requests.get(url)
    print(r.status_code, f"{idx}/{len(stock_code)-1} 작업중", end="\r")
    soup = bs(r.content, 'lxml')
    # 종목명
    stock_name = soup.select_one("dl.blind > dd:nth-child(3)").text[4:]
    # 현재가
    today_price = int(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[1].replace(",", ""))
    # 변동금액
    change = soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[3:5]
    change = -int(change[1].replace(",", "").replace("\n,,", "")) if change[0] == "하락" else int(change[1].replace(",", "").replace("\n", ""))
    # 변동률
    percent = "".join(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[16:30])
    percent = percent.replace("마이너스", "-").replace("퍼센트", "%").replace("\n", "").replace("플러스", "")
    # 전일가
    yester_price = int(soup.select_one("dl.blind > dd:nth-child(6)").text[4:].replace(",", ""))
    # 고가
    hi = soup.select_one("dl.blind > dd:nth-child(8)").text[3:].replace(",", "")
    # 상한가
    top = soup.select_one("dl.blind > dd:nth-child(9)").text[4:].replace(",", "")
    # 저가
    low = soup.select_one("dl.blind > dd:nth-child(10)").text[3:].replace(",", "")
    # 하한가
    bottom = soup.select_one("dl.blind > dd:nth-child(11)").text[4:].replace(",", "")
    # 거래량
    volume = soup.select_one("dl.blind > dd:nth-child(12)").text[4:].replace(",", "")

    result = (code, stock_name, today_price, change, percent, yester_price, hi, top, low, bottom, volume)
    columns = ["종목코드", "종목명", "현재가", "변동금액", "변동률", "전일가",
           "고가", "상한가", "저가", "하한가", "거래량"  ]    
    df = pd.DataFrame([result], columns=columns)
    # 오늘기준 연도, 달 출력
    year, month = year_month()
    # Database 쿼리창 오픈
    conn = dbconnect()
    df.to_sql(f'stock_price_{year}_{month:02d}', con=conn,  if_exists="append", index=False)
    conn.close()
    print(f"{idx+1}/{len(stock_code)} {stock_name}DB 저장 완료", end="\r")
    time.sleep(5)

ValueError: invalid literal for int() with base 10: 'АЁ 79900'

In [163]:
for idx, code in enumerate(stock_code):
    url =f"https://finance.naver.com/item/main.naver?code={code}"
    r = requests.get(url)
    print(r.status_code, f"{idx+1}/{len(stock_code)} {code} 작업중", end="\r")
    soup = bs(r.content, 'lxml')
    # 종목명
    stock_name = soup.select_one("dl.blind > dd:nth-child(3)").text[4:]
    # 현재가
    today_price = int(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[1].replace(",", ""))
    # 변동금액
    change = soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[3:5]
    change = -int(change[1].replace(",", "").replace("\n,,", "")) if change[0] == "하락" else int(change[1].replace(",", "").replace("\n", ""))
    # 변동률
    percent = "".join(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[16:30])
    percent = percent.replace("마이너스", "-").replace("퍼센트", "%").replace("\n", "").replace("플러스", "")
    # 전일가
    yester_price = int(soup.select_one("dl.blind > dd:nth-child(6)").text[4:].replace(",", ""))
    # 고가
    hi = soup.select_one("dl.blind > dd:nth-child(8)").text[3:].replace(",", "")
    # 상한가
    top = soup.select_one("dl.blind > dd:nth-child(9)").text[4:].replace(",", "")
    # 저가
    low = soup.select_one("dl.blind > dd:nth-child(10)").text[3:].replace(",", "")
    # 하한가
    bottom = soup.select_one("dl.blind > dd:nth-child(11)").text[4:].replace(",", "")
    # 거래량
    volume = soup.select_one("dl.blind > dd:nth-child(12)").text[4:].replace(",", "")

    result = (code, stock_name, today_price, change, percent, yester_price, hi, top, low, bottom, volume)
    columns = ["종목코드", "종목명", "현재가", "변동금액", "변동률", "전일가",
           "고가", "상한가", "저가", "하한가", "거래량"  ]    
    df = pd.DataFrame([result], columns=columns)
    # 오늘기준 연도, 달 출력
    year, month = year_month()
    # Database 쿼리창 오픈
#     conn = dbconnect()
#     df.to_sql(f'stock_price_{year}_{month:02d}', con=conn,  if_exists="append", index=False)
#     conn.close()
    print(f"{idx+1}/{len(stock_code)} {stock_name}DB 저장 완료", end="\r")
    time.sleep(5)

KeyboardInterrupt:

In [160]:
code

'4'

In [162]:
soup

<html lang="ko">
<head>
<title> : 네이버페이 증권</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="text/javascript" http-equiv="Content-Script-Type"/>
<meta content="text/css" http-equiv="Content-Style-Type"/>
<meta content="네이버페이 증권" name="apple-mobile-web-app-title"/>
<meta content="https://finance.naver.com/item/main.naver?code=" property="og:url"/>
<meta content=" - 네이버페이 증권 : 네이버페이 증권" property="og:title"/>
<meta content="관심종목의 실시간 주가를 가장 빠르게 확인하는 곳" property="og:description"/>
<meta content="https://ssl.pstatic.net/static/m/stock/im/2016/08/og_stock-200.png" property="og:image"/>
<meta content="article" property="og:type"/>
<meta content="" property="og:article:thumbnailUrl"/>
<meta content="네이버페이 증권" property="og:article:author"/>
<meta content="http://FINANCE.NAVER.COM" property="og:article:author:url"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/css/finance_header.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/css/newstock.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/css/common.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/css/layout.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/css/main.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/css/newstock2.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/css/newstock3.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/css/world.css" rel="stylesheet" type="text/css"/>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/js/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/js/release/common.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/js/jindoComponent/jindo.Component.1.0.3.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/js/nhn.autocomplete.stock.js" type="text/javascript"></script>
<script>
	var ieVersion = (function () {
        var version = -1;
        if (
          navigator.appName == 'Microsoft Internet Explorer' &&
          navigator.userAgent.toLowerCase().indexOf('msie') != -1 &&
          new RegExp('MSIE ([0-9]{1,}[\./0-9]{0,})').exec(navigator.userAgent) != null
        ) {
          version = parseInt(RegExp.$1);
        }
        return version;
      })();
</script>
<link href="https://ssl.pstatic.net/imgstock/favi/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<script type="text/javascript">
    (function(){
		document.write(
				[
					'<link rel="apple-touch-icon-precomposed" href="https://ssl.pstatic.net/imgstock/favi/favicon-96x96.png"/>',
					'<link rel="apple-touch-icon-precomposed" sizes="180x180" href="https://ssl.pstatic.net/imgstock/favi/favicon-180x180.png"/>',
					'<link rel="apple-touch-icon-precomposed" sizes="192x192" href="https://ssl.pstatic.net/imgstock/favi/favicon-192x192.png"/>',
					'<link rel="icon" type="image/png" sizes="16x16" href="https://ssl.pstatic.net/imgstock/favi/favicon-16x16.png"/>',
					'<link rel="icon" type="image/png" sizes="32x32" href="https://ssl.pstatic.net/imgstock/favi/favicon-32x32.png"/>',
					'<link rel="icon" type="image/png" sizes="96x96" href="https://ssl.pstatic.net/imgstock/favi/favicon-96x96.png"/>',
					'<link rel="icon" type="image/png" sizes="192x192" href="https://ssl.pstatic.net/imgstock/favi/favicon-192x192.png"/>'
				]
			.join('\n')
		);
    })();
    </script>
</head>
<body onload="getGNB();">
<script type="text/javascript">







var nsc="finance.stockend";


var ccsrv="cc.naver.com";




	var gnb_service='finance';



var gnb_logout=document.URL; //GNB에서 로그아웃 후 redirect 될 URL
var gnb_searchbox='off'; //미니 검색창을 on 할지 off 할지. default는 off
var gnb_shortnick='off'; //닉네임 말줄임(10자)을 on할지 off 할지. default는 off.


var gnb_naverme_layer_open_callback = function(){
	   var naverLayerSize = gnbNaverMeLayer.getLayerSize();

		var me_layers = document.getElementById("me_layers");
		me_layers.width=naverLayerSize.width;
		me_layers.height=naverLayerSize.height;};

var gnb_naverme_layer_close_callback = function(){

			var me_layers = document.getElementById("me_layers");
			me_layers.width="0";
			me_layers.height="0";};
</script>
<div id="u_skip">
<a href="#menu" tabindex="1"><span>메인 메뉴로 바로가기</span></a>
<a href="#middle" tabindex="2"><span>본문으로 바로가기</span></a>
</div>
<div id="header">
<div class="header_area">
<div class="header_inner">
<div class="logo_area">
<h1 class="service">
<a class="logo_link" href="https://www.naver.com/" onclick="clickcr(this, 'STA.naver', '', '', event);">
<svg fill="none" height="22" viewbox="0 0 22 22" width="22" xmlns="http://www.w3.org/2000/svg">
<path d="M22 11C22 13.1756 21.3549 15.3023 20.1462 17.1113C18.9375 18.9202 17.2195 20.3301 15.2095 21.1627C13.1995 21.9952 10.9878 22.2131 8.85401 21.7886C6.72022 21.3642 4.76021 20.3166 3.22183 18.7782C1.68345 17.2398 0.635805 15.2798 0.211368 13.146C-0.213069 11.0122 0.00476298 8.80047 0.837327 6.79048C1.66989 4.78049 3.07979 3.06253 4.88873 1.85383C6.69768 0.645137 8.82441 0 11 0C13.9174 0 16.7153 1.15893 18.7782 3.22183C20.8411 5.28473 22 8.08262 22 11ZM12.8398 5.83V11.3602L8.98976 5.83H5.83V16.1838H9.1575V10.637L13.0075 16.17H16.1783V5.83H12.8398Z" fill="#000"></path>
</svg>
<span class="blind">네이버</span>
</a>
<a class="logo_link" href="https://new-m.pay.naver.com/" onclick="clickcr(this, 'STA.pay', '', '', event);">
<svg fill="none" height="22" viewbox="0 0 37 22" width="37" xmlns="http://www.w3.org/2000/svg">
<path d="M34.4319 5.21944L31.3913 12.1478L27.9518 5.21944H25.3072L30.1783 14.8317L28.1703 19.3358H30.7384L37 5.2331L34.4319 5.21944ZM23.6171 15.9331H21.1037V14.9328C20.1894 15.7342 19.0108 16.1685 17.7953 16.1518C14.7901 16.1518 12.4379 13.692 12.4379 10.5763C12.4379 7.46057 14.7874 5.00079 17.7953 5.00079C19.0104 4.9833 20.189 5.41657 21.1037 6.21701V5.21944H23.6171V15.9331ZM21.3987 10.5899C21.3987 8.57019 19.9891 7.03694 18.1204 7.03694C16.2517 7.03694 14.842 8.57019 14.842 10.5899C14.842 12.6097 16.249 14.1429 18.1204 14.1429C19.9918 14.1429 21.3987 12.596 21.3987 10.5899ZM0.00819554 19.3358H2.63088V15.023C3.52823 15.7695 4.66309 16.1699 5.83001 16.1518C8.83516 16.1518 11.1901 13.692 11.1901 10.5763C11.1901 7.46057 8.83789 5.00079 5.83001 5.00079C4.61166 4.9789 3.42899 5.4126 2.51341 6.21701V5.21944H0L0.00819554 19.3358ZM5.51856 7.03694C7.38722 7.03694 8.79691 8.57019 8.79691 10.5899C8.79691 12.6097 7.38722 14.1429 5.51856 14.1429C3.6499 14.1429 2.24021 12.6097 2.24021 10.5899C2.24021 8.57019 3.63351 7.03694 5.51856 7.03694Z" fill="#000"></path>
</svg>
<span class="blind">페이</span>
</a>
<a class="logo_link" href="/" onclick="clickcr(this, 'STA.finance', '', '', event);">
<svg fill="none" height="22" viewbox="0 0 34 22" width="34" xmlns="http://www.w3.org/2000/svg">
<path d="M2.43006 8.88998L1.85406 6.99998C5.29206 6.31598 7.00206 5.34398 7.45206 4.31798H2.71806V2.35598H14.3641V4.31798H9.75606C9.70206 4.65998 9.61206 4.98398 9.46806 5.28998L15.2101 6.98198L14.4901 8.88998L8.02806 6.92798C6.84006 7.75598 5.00406 8.40398 2.43006 8.88998ZM0.612061 11.5V9.53798H16.4521V11.5H0.612061ZM6.53406 12.796H10.5301C13.2301 12.796 14.7961 14.128 14.7961 15.91C14.7961 17.71 13.2301 19.024 10.5301 19.024H6.53406C3.85206 19.024 2.28606 17.71 2.28606 15.91C2.28606 14.128 3.85206 12.796 6.53406 12.796ZM6.96606 17.044H10.1161C11.7901 17.044 12.4921 16.594 12.4921 15.892C12.4921 15.19 11.7901 14.776 10.1161 14.776H6.96606C5.29206 14.776 4.57206 15.19 4.57206 15.892C4.57206 16.594 5.29206 17.044 6.96606 17.044Z" fill="#000"></path>
<path d="M25.1904 13.354V11.536H29.4564V2.03198H31.7604V15.334H29.4564V13.354H25.1904ZM21.3384 10.564C20.9244 10.582 20.5464 10.582 20.1684 10.582H17.4504L17.3604 8.61998H20.3844C21.5004 8.61998 22.9584 8.56598 24.4884 8.45798C24.7224 6.99998 24.8484 5.63198 24.8664 4.62398H18.4404V2.66198H27.0984V3.56198C27.0984 5.16398 26.9724 6.76598 26.7564 8.25998L28.2684 8.09798L28.5024 10.006C26.9724 10.222 25.2264 10.384 23.5704 10.474C23.4984 11.5 23.3904 12.562 23.2644 13.714L21.0684 13.588C21.1764 12.508 21.2664 11.536 21.3384 10.564ZM22.4724 14.254V16.756H32.3724V18.844H20.1684V14.254H22.4724Z" fill="#000"></path>
</svg>
<span class="blind">증권</span>
</a>
</h1>
</div>
<div class="right_area">
<div class="search_area">
<form action="/search/search.naver" method="get" name="search" onsubmit="return delayed_submit(this)" style="margin:0; padding:0;">
<label class="blind" for="stock_items">증권 종목명·지수명 검색</label>
<input accesskey="s" autocomplete="off" class="search_input" id="stock_items" name="query" placeholder="종목명·지수명 입력" title="종목명·지수명 검색" type="text"/>
<input id="_endUrl" name="endUrl" type="hidden" value=""/>
<button class="search_button" onclick="clickcr(this, 'STA.search', '', '', event);" type="button">
<svg fill="none" height="16" viewbox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg">
<path clip-rule="evenodd" d="M6.9999 2.59996C4.56985 2.59996 2.5999 4.56991 2.5999 6.99996C2.5999 9.43002 4.56985 11.4 6.9999 11.4C9.42996 11.4 11.3999 9.43002 11.3999 6.99996C11.3999 4.56991 9.42996 2.59996 6.9999 2.59996ZM1.3999 6.99996C1.3999 3.90717 3.90711 1.39996 6.9999 1.39996C10.0927 1.39996 12.5999 3.90717 12.5999 6.99996C12.5999 10.0928 10.0927 12.6 6.9999 12.6C3.90711 12.6 1.3999 10.0928 1.3999 6.99996Z" fill="#404048" fill-rule="evenodd"></path>
<path clip-rule="evenodd" d="M10.2421 10.2424C10.4765 10.0081 10.8564 10.0081 11.0907 10.2424L14.424 13.5758C14.6583 13.8101 14.6583 14.19 14.424 14.4243C14.1897 14.6586 13.8098 14.6586 13.5755 14.4243L10.2421 11.091C10.0078 10.8567 10.0078 10.4768 10.2421 10.2424Z" fill="#404048" fill-rule="evenodd"></path>
</svg>
<span class="blind">검색</span>
</button>
<div class="auto_area">
<span class="blind">자동완성</span>
<div id="autoFrame" style="display: none;">
<div class="wrap" id="atcmp" style="display:none;">
<div class="wrap_in">
<div class="words">
<ul class="_resultBox">
<li>
<a class="_au_real_list" href="#" onclick="clickcr(this, 'AUT.list', '', '', event); return false;">
<span class="num _au_real_list">@code@</span>
<span class="_au_real_list">@txt@</span>
<span class="type _au_real_list">@market@</span>
</a>
<div class="_au_full" style="display:none">@full_txt@</div>
<div class="_au_code" style="display:none">@in_code@</div>
<div class="_au_name" style="display:none">@in_name@</div>
<div class="_au_link" style="display:none">@in_link@</div>
<div class="_au_market" style="display:none">@in_market@</div>
</li>
</ul>
<div class="search_notice">
<p class="text">
												공모주와 해외 종목은 모바일 페이지로 이동합니다.
											</p>
</div>
</div>
</div>
<!-- 현재 자동완성 기능을 사용하고 계십니다 -->
<div class="wrap" id="atcmpIng" style="display:none;">
<div class="wrap_in">
<div class="words">
<p class="msg">
												현재 자동완성 기능을 사용하고 계십니다.
											</p>
</div>
</div>
</div>
<!--// 현재 자동완성 기능을 사용하고 계십니다 -->
<!-- 자동완성 기능이 활성화 -->
<div class="wrap" id="atcmpStart" style="display:none;">
<div class="wrap_in">
<div class="words">
<p class="msg">
												자동완성 기능이 활성화되었습니다.
											</p>
</div>
</div>
</div>
</div>
</div>
</div>
</form>
</div>
<div class="gnb_area">
<div id="gnb">
<script charset="EUC-KR" type="text/javascript">
							var gnb_service = "finance";
							var gnb_template = location.protocol === "http:" ? "gnb_quirks_euckr" : "gnb_utf8" ;
							var gnb_logout=encodeURIComponent(location.href);
							var gnb_brightness = 1;
							var gnb_one_naver = 0;
						</script>
<script charset="utf-8" src="https://ssl.pstatic.net/static.gn/templates/gnb_utf8.nhn?20250407" type="text/javascript">
</script>
</div>
</div>
</div>
</div>
</div>
<div class="lnb_area">
<div class="lnb_inner">
<div id="menu">
<ul class="menu">
<li class="m1 first"><a href="/" onclick="clickcr(this, 'LNB.home', '', '', event);"><span class="tx">증권 홈</span></a></li>
<li class="m2 on"><a href="/sise/" onclick="clickcr(this, 'LNB.sise', '', '', event);"><span class="tx">국내증시</span><span class="blind">선택됨</span></a></li>
<li class="m3"><a href="/world/" onclick="clickcr(this, 'LNB.world', '', '', event);"><span class="tx">해외증시</span></a></li>
<li class="m4"><a href="/marketindex/" onclick="clickcr(this, 'LNB.market', '', '', event);"><span class="tx">시장지표</span></a></li>
<li class="m6"><a href="/research/" onclick="clickcr(this, 'LNB.research', '', '', event);"><span class="tx">리서치</span></a></li>
<li class="m7"><a href="/news/"><span class="tx">뉴스</span></a></li>
<li class="m8"><a href="/mystock/" onclick="clickcr(this, 'LNB.mystock', '', '', event);"><span class="tx">MY</span></a></li>
</ul>
</div>
</div>
</div>
<script type="text/JavaScript">
		/* lcs 집계 */
        ;(function(){
            var eventType = "onpageshow" in window ? "pageshow" : "load";
            jindo.$Fn(function(){
                lcs_do();
            }).attach(window, eventType);
        })();

		/* 검색 자동완성 [ 인자1 : 검색input의 ID, 인자2 : iframe 태그 ID ]   */
		// AutoComplete 생성
		var acDomain = "ac.stock.naver.com";
		if (location.hostname.indexOf("staging-") > -1) {
			acDomain = "staging-" + acDomain;
		} else if (location.hostname.indexOf("test-") > -1) {
			acDomain = "test-" + acDomain;
		} else if (location.hostname.indexOf("dev-") > -1 || location.hostname.indexOf("localhost") > -1 || location.hostname.indexOf("local-") > -1) {
			acDomain = "dev-" + acDomain;
		}

        var acUrl = "https://" + acDomain + "/ac";

		smartSearch = new nhn.Autocomplete(
			// InputManager 생성
			new nhn.AcInputManager(jindo.$("stock_items")),
			// DataManager 생성
			new nhn.AcDataManager(acUrl, "xhr", "get", {}),
			// ViewManager 생성
			new nhn.AcStockViewManager(jindo.$("autoFrame"), jindo.$("nautocomplete"), {
                                        strMax: 200,
                                        listMax: [7, 2, 2],
                                        aRedirectUrl: [
										"https://" + window.location.hostname,
                            			"https://finance.naver.com",
                            			"https://finance.naver.com"],
										mobileUrl: "https://m.stock.naver.com"}),
			// Autocomplete Option
            {formId:"search", cookieDomain:location.hostname, cookieName:"NaverCommonStock_disable"});

			smartSearch.attach({
	            onFocus: function () {
	                var weInput = jindo.$Element('stock_items');
	                if (weInput && weInput.hasClass("snb_default")) {
	                        weInput.text("");
	                        weInput.removeClass('snb_default');
	                }
	            }
	        });

		/* 통합검색  start ----->  */
		var sSearchHintText = '종목명·지수명·환율명·원자재명 입력';
		function itegrationSearch() {
			var query = jindo.$('stock_items').value;

			if ( query == ''  || encodeURIComponent(query) == encodeURIComponent(sSearchHintText))
			{
				alert ( '검색어를 입력해 주세요.' );
				return;
			}

            var url = "https://search.naver.com/search.naver?sm=sta_hty.finance&where=nexearch&ie=UTF8&query=" + encodeURIComponent(query);
            window.open(url, "_blank");

			return false;
		}

		function delayed_submit(object) {
			if (navigator.userAgent.indexOf('MSIE') == -1) {
				window.setTimeout(function() {stock_search(object)}, 300);
			} else {
				stock_search(object);
			}
			return false;
		}

		function stock_search (object) {
			// endUrl check
			if (object.endUrl.value) {
				if (object.endUrl.value.startsWith("https://m.stock.naver.com")) {
					// 검색정보 초기화
					var _endUrl = object.endUrl.value;
					object.query.value = "";
					object.endUrl.value = "";
					document.getElementById("atcmp").style.display="none";
					window.open(_endUrl, "_blank");
				} else {
					location.href = object.endUrl.value;
				}

				return;
			}

			// query check
			query = object.query.value.replace(/^\s*/,'').replace(/\s*$/,'');	// trim
			object.query.value=query;

			if ( query == '' || query == sSearchHintText.replace(/^\s*/,'').replace(/\s*$/,''))
			{
				alert ( '검색어를 입력해 주세요.' );
				return;
			}
			else {
				object.submit();
			}
		}
		/* <---------- 통합검색  end */

		function popup()
		{
			win = window.open('/template/group_limit_pop.jsp','finan_popup','width=569 height=278 scrollbars=no status=no');
			win.focus();
		}
	</script>
<iframe frameborder="0" height="0" id="me_layers" name="test" scrolling="no" style="display:block;top: 22px; right: 209px; position: absolute; z-index: 15;" title="네이버미 영역" width="0"></iframe>
</div>
<div id="wrap">
<script language="javascript" src="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/js/ellipse.js"></script>
<script type="text/javascript">
	function financialInfoCommentToggle() {
		if(jindo.$Element(jindo.$$.getSingle("div.ly_moreifrs")).visible()) {
			jindo.$Element(jindo.$$.getSingle("a.more_ifrs")).html("항목별 상세기준 보기");
			jindo.$Element(jindo.$$.getSingle("a.more_ifrs")).removeClass("fd");
		} else {
			jindo.$Element(jindo.$$.getSingle("a.more_ifrs")).html("항목별 상세기준 닫기");
			jindo.$Element(jindo.$$.getSingle("a.more_ifrs")).addClass("fd");
		}
		jindo.$Element(jindo.$$.getSingle("div.ly_moreifrs")).toggle();
	}

</script>
<title>네이버페이 증권</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="text/javascript" http-equiv="Content-Script-Type"/>
<meta content="text/css" http-equiv="Content-Style-Type"/>
<meta content="네이버페이 증권" name="apple-mobile-web-app-title"/>
<meta content="네이버페이 증권" property="og:title"/>
<meta content="https://ssl.pstatic.net/static/m/stock/im/2016/08/og_stock-200.png" property="og:image"/>
<meta content="https://finance.naver.com" property="og:url"/>
<meta content="국내 해외 증시 지수, 시장지표, 뉴스, 증권사 리서치 등 제공" property="og:description"/>
<meta content="article" property="og:type"/>
<meta content="" property="og:article:thumbnailUrl"/>
<meta content="네이버페이 증권" property="og:article:author"/>
<meta content="http://FINANCE.NAVER.COM" property="og:article:author:url"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/css/finance_header.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/css/finance.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/css/newstock3.css" rel="stylesheet" type="text/css"/>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/js/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/js/release/common.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/js/jindoComponent/jindo.Component.1.0.3.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250326145749/js/nhn.autocomplete.stock.js" type="text/javascript"></script>
<script>
	var ieVersion = (function () {
        var version = -1;
        if (
          navigator.appName == 'Microsoft Internet Explorer' &&
          navigator.userAgent.toLowerCase().indexOf('msie') != -1 &&
          new RegExp('MSIE ([0-9]{1,}[\./0-9]{0,})').exec(navigator.userAgent) != null
        ) {
          version = parseInt(RegExp.$1);
        }
        return version;
      })();
</script>
<link href="https://ssl.pstatic.net/imgstock/favi/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<script type="text/javascript">
    (function(){
		document.write(
				[
					'<link rel="apple-touch-icon-precomposed" href="https://ssl.pstatic.net/imgstock/favi/favicon-96x96.png"/>',

In [161]:
stock_code[45]

'484870'

# 함수형 프로그래밍으로 코드 변경하기

In [2]:
def stock_info_get(code):
    url =f"https://finance.naver.com/item/main.naver?code={code}"
    r = requests.get(url)
    print(r.status_code, f"{idx+1}/{len(stock_code)} {code} 작업중", end="\r")
    soup = bs(r.content, 'lxml')
    # 종목명
    stock_name = soup.select_one("dl.blind > dd:nth-child(3)").text[4:]
    # 현재가
    today_price = int(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[1].replace(",", ""))
    # 변동금액
    change = soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[3:5]
    change = -int(change[1].replace(",", "").replace("\n,,", "")) if change[0] == "하락" else int(change[1].replace(",", "").replace("\n", ""))
    # 변동률
    percent = "".join(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[16:30])
    percent = percent.replace("마이너스", "-").replace("퍼센트", "%").replace("\n", "").replace("플러스", "")
    # 전일가
    yester_price = int(soup.select_one("dl.blind > dd:nth-child(6)").text[4:].replace(",", ""))
    # 고가
    hi = soup.select_one("dl.blind > dd:nth-child(8)").text[3:].replace(",", "")
    # 상한가
    top = soup.select_one("dl.blind > dd:nth-child(9)").text[4:].replace(",", "")
    # 저가
    low = soup.select_one("dl.blind > dd:nth-child(10)").text[3:].replace(",", "")
    # 하한가
    bottom = soup.select_one("dl.blind > dd:nth-child(11)").text[4:].replace(",", "")
    # 거래량
    volume = soup.select_one("dl.blind > dd:nth-child(12)").text[4:].replace(",", "")

    result = (code, stock_name, today_price, change, percent, yester_price, hi, top, low, bottom, volume)
    columns = ["종목코드", "종목명", "현재가", "변동금액", "변동률", "전일가",
           "고가", "상한가", "저가", "하한가", "거래량"  ]    
    df = pd.DataFrame([result], columns=columns)
    # 오늘기준 연도, 달 출력
    time.sleep(5)
    return df, stock_name

In [3]:
from dbio import *

In [4]:
stock_code = stock_codes()
for idx, code in enumerate(stock_code):
    print(f"{idx}/{len(stock_code)-1} {code} 작업중", end="\r")
    df, stock_name = stock_info_get(code)
    to_stock_db(idx, code, stock_name, df)

ValueError: invalid literal for int() with base 10: 'АЁ 24500'